openapi: 3.0.1
paths:
  /items:
    get:
      operationId: getItems
      responses:
        "200":
          description: getItems 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      operationId: createOrIncrease
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemController.ItemRequest'
        required: true
      responses:
        "200":
          description: createOrIncrease 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
  /items/{id}:
    get:
      operationId: getItemById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: getItemById 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    put:
      operationId: updateItem
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemController.ItemRequest'
        required: true
      responses:
        "200":
          description: updateItem 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    delete:
      operationId: deleteItem
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: deleteItem 200 response
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        name:
          type: string
        quantity:
          type: integer
          format: int32
      description: Represents a shopping list item
    ItemController.ItemRequest:
      required:
      - name
      - quantity
      type: object
      properties:
        name:
          type: string
        quantity:
          type: integer
          format: int32
