version: '3.8'
services:
  shopping-app:
    container_name: backend
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
  vue-frontend:
    build:
      context: ./frontend      
      dockerfile: Dockerfile
    ports:
      - "8081:80"     
    restart: unless-stopped