# version: '3.8'
services:
  backend:
    build:
      context: ./shopping-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    container_name: backend-container
  vue-frontend:
    build:
      context: ./frontend      
      dockerfile: Dockerfile
    ports:
      - "8081:80"     
    restart: unless-stopped
