version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    ports:
      - "8080:8080"
  vue-frontend:
    build:
      context: ./frontend      
      dockerfile: Dockerfile
    ports:
      - "8081:80"     
    restart: unless-stopped
