apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app
  labels:
    app: shopping-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-app
  template:
    metadata:
      labels:
        app: shopping-app
    spec:
      containers:
        - name: shopping-app
          image: ragoit00/shopping-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MICRONAUT_SERVER_PORT
              value: "8080"
