apiVersion: v1
kind: Service
metadata:
  name: vue-frontend-service
spec:
  type: NodePort # or LoadBalancer depending on your environment
  selector:
    app: vue-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80